settings:
  commit_msg: ":zap: Update README with recent activity"
  max_lines: 5
  readme_file: "./README.md"
  disabled_events:
    - "comments"

messages:
  opened_pr: "ğŸš€ Opened PR #{ID} in {REPO}"
  merged_pr: "ğŸ”€ Merged PR #{ID} in {REPO}"
  opened_issue: "ğŸ› Opened issue #{ID} in {REPO}"
  closed_issue: "âœ… Closed issue #{ID} in {REPO}"
  commented_on_issue: "ğŸ’¬ Commented on #{ID} in {REPO}"
  commented_on_pr: "ğŸ’¬ Commented on PR #{ID} in {REPO}"
  created_repo: "ğŸŠ Created new repo {REPO}"
  forked_repo: "ğŸ´ Forked {FORK} from {REPO}"
  starred_repo: "â­ Starred {REPO}"
  created_release: "ğŸ‰ Released {RELEASE} in {REPO}"
