settings:
  username: whanyu1212
  commit_msg: "âš¡ Update README with the recent activity"
  max_lines: 5
  date:
    text: "Last Updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"

messages:
  comments: "ğŸ’¬ Commented on {ID} in {REPO}"
  issue_opened: "â— Opened issue {ID} in {REPO}"
  issue_closed: "âœ… Closed issue {ID} in {REPO}"
  pr_opened: "âš¡ Opened PR {ID} in {REPO}"
  pr_merged: "ğŸ‰ Merged PR {ID} in {REPO}"
  pr_closed: "âŒ Closed PR {ID} in {REPO}"
  push: "â¬†ï¸ Pushed {AMOUNT} commit(s) to {REPO}"
  release: "ğŸš€ Released {ID} in {REPO}"
  star: "â­ Starred {REPO}"
  fork: "ğŸ´ Forked {REPO}"
  wiki: "ğŸ“ Updated wiki in {REPO}"
  member: "ğŸ‘¥ Became collaborator on {REPO}"
  create_repo: "ğŸ Created new repository {REPO}"
  review: "ğŸ‘€ Reviewed {ID} in {REPO}"
