settings:
  username: whanyu1212
  commit_msg: "âš¡ Update README with the recent activity"
  max_lines: 5
  url_text: "{REPO}{ID}"

messages:
  push: "â¬†ï¸ Pushed {AMOUNT} commit(s) to {REPO}"
  issue_opened: "â—ï¸ Opened issue {ID} in {REPO}"
  issue_closed: "âœ”ï¸ Closed issue {ID} in {REPO}"
  pr_opened: "ğŸ’ª Opened PR {ID} in {REPO}"
  pr_merged: "ğŸ‰ Merged PR {ID} in {REPO}"
  pr_closed: "ğŸš« Closed PR {ID} in {REPO}"
  create_repo: "ğŸ“” Created new repository {REPO}"
  fork_repo: "ğŸ”± Forked {REPO}"
  star_repo: "â­ Starred {REPO}"
  release: "ğŸš€ Released {ID} in {REPO}"
  wiki: "ğŸ“– Updated wiki in {REPO}"
  review: "ğŸ‘€ Reviewed {ID} in {REPO}"
  comment: "ğŸ’¬ Commented on {ID} in {REPO}"
  member: "ğŸ¤ Became collaborator on {REPO}"
